version: "3.8"
services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      retries: 10

  wordpress:
    image: wordpress:6.6-php8.2-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_ENV: ${WP_ENV}
      # Enable debug in the running wordpress (web) container so PHP/WordPress
      # errors are written when serving pages
      WP_DEBUG: 1
      WP_DEBUG_LOG: /var/www/html/wp-content/logs/php-errors.log
      WP_DEBUG_DISPLAY: 1
      WP_DISABLE_FATAL_ERROR_HANDLER: 1
    volumes:
      - wp_html:/var/www/html
      - ./wp-content/themes/tvs-theme:/var/www/html/wp-content/themes/tvs-theme
      - ./wp-content/plugins/tvs-virtual-sports:/var/www/html/wp-content/plugins/tvs-virtual-sports
      - ./logs:/var/www/html/wp-content/logs

  cli:
    image: wordpress:cli-php8.2
    depends_on:
      - db
      - wordpress
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_ENV: ${WP_ENV}
      WP_DEBUG: 1
      # Keep same debug log path as the web container so logs are collected
      WP_DEBUG_LOG: /var/www/html/wp-content/logs/php-errors.log
      WP_DEBUG_DISPLAY: 1
      WP_DISABLE_FATAL_ERROR_HANDLER: 1
    volumes:
      - wp_html:/var/www/html
      - ./wp-content/themes/tvs-theme:/var/www/html/wp-content/themes/tvs-theme
      - ./wp-content/plugins/tvs-virtual-sports:/var/www/html/wp-content/plugins/tvs-virtual-sports
      - ./scripts:/scripts
      - ./logs:/var/www/html/wp-content/logs
    entrypoint: wp

volumes:
  db_data:
  wp_html:
