services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      retries: 10

  wordpress:
    image: wordpress:6.6-php8.2-apache
    #image: ghcr.io/docker-library/wordpress:6.6-php8.2-apache
    #image: bitnami/wordpress:6.6.2
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      ALLOW_EMPTY_PASSWORD: "yes"
      WP_DEBUG: 1
      WP_DEBUG_LOG: /var/www/html/wp-content/logs/php-errors.log
      WP_DEBUG_DISPLAY: 1
      WP_DISABLE_FATAL_ERROR_HANDLER: 1
    volumes:
      # Kjernen ligger i dette volume
      - wordpress_data:/var/www/html
      # Mount kun ditt tema og din plugin
      - ./wp-content/themes/tvs-theme:/var/www/html/wp-content/themes/tvs-theme
      - ./wp-content/plugins/tvs-virtual-sports:/var/www/html/wp-content/plugins/tvs-virtual-sports
      - ./logs:/var/www/html/wp-content/logs

  cli:
    image: wordpress:cli-php8.2
    depends_on:
      - db
      - wordpress
    working_dir: /var/www/html
    entrypoint: ["wp"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_DEBUG: 1
      WP_DEBUG_LOG: /var/www/html/wp-content/logs/php-errors.log
      WP_DEBUG_DISPLAY: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes/tvs-theme:/var/www/html/wp-content/themes/tvs-theme
      - ./wp-content/plugins/tvs-virtual-sports:/var/www/html/wp-content/plugins/tvs-virtual-sports
      - ./logs:/var/www/html/wp-content/logs
      - ./scripts:/scripts

volumes:
  db_data:
  wordpress_data:
