name: Publish flattened tree (no submodules)

on:
  push:
    branches: [ main ]   # endre hvis dere bruker en annen primærgren
  workflow_dispatch:

permissions:
  contents: write   # trengs for å pushe til repoet

jobs:
  flatten:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules, no persisted creds)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false   # <-- viktig: ikke skriv inn egne creds i repoet

      - name: Prepare clean workdir
        run: |
          set -euo pipefail
          rm -rf /tmp/flatten
          mkdir -p /tmp/flatten

          # Kopiér hele infra-repoet, men dropp git-metadata
          rsync -a \
            --exclude '.git' \
            --exclude '.github/workflows/flatten.yml' \
            ./ /tmp/flatten/

      - name: Replace submodules with actual contents
        run: |
          set -euo pipefail
          mkdir -p /tmp/flatten/wp-content/plugins/tvs-virtual-sports
          mkdir -p /tmp/flatten/wp-content/themes/tvs-theme

          rsync -a --delete --exclude '.git' \
            ./wp-content/plugins/tvs-virtual-sports/ \
            /tmp/flatten/wp-content/plugins/tvs-virtual-sports/

          rsync -a --delete --exclude '.git' \
            ./wp-content/themes/tvs-theme/ \
            /tmp/flatten/wp-content/themes/tvs-theme/

          rm -f /tmp/flatten/.gitmodules || true

      - name: Optionally prune noise
        run: |
          set -euo pipefail
          find /tmp/flatten -type d -name "node_modules" -prune -exec rm -rf {} + || true
          rm -rf /tmp/flatten/logs || true

      - name: Commit & Force-push to 'flattened' branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          cd /tmp/flatten

          git init
          git config user.name "TVS Infra Build Bot"
          git config user.email "ci@virtualsports.online"

          # Global fallback: alle https://github.com/... vil bruke token automatisk
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

          git add .
          git commit -m "chore: flattened tree for Codex/Copilot @ ${SHA}"
          git branch -M flattened

          # Eksplicit remote med token (belt & bukseseler)
          git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"

          # Vis remote uten å eksponere token
          git remote -v | sed 's/x-access-token:.*@/x-access-token:***@/g'

          git push -f origin flattened

      - name: Summary
        run: |
          echo "Flattened branch published."
